FROM mono:5.8.0 AS mono-env
WORKDIR /app
COPY . ./
RUN curl -o ./nuget.exe https://dist.nuget.org/win-x86-commandline/v4.5.1/nuget.exe
ENTRYPOINT ["mono", "nuget.exe", "restore", "-PackagesDirectory", "./packages"]
